language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install flake8 scons
script:
- pip install -e .
- python setup.py test
- flake8
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: Ef7Go3bndaYDU5M4uy0gf7ca22XjsQXXWGLlZkJqUChdKsJ2Yd5lqO0Hw2XMXwnJOZybC2tIwR9EtMtaR19IltZKW3KIHx3j3NemajCFkF4RF6fLHyfBFqAR0x/KINhBPnd1jEUiEEZItKvZjhTKrfKfuILDfnBZji3jXW4nrhlD4XtiuYlXPimpWk+1UC71vhu4kHem6Pasq53odHKzWG9itPwHE4Rft86lp7WH0DNAqPBtns2Qx7Mw7onPvN05ulVDX+Tqs5e5fSALmn0sUmWT5Iyvv2MzZOxevRaLd66UvD6Kumrc6+U79mxve0GdsuP13a4WLfIwjYpy7Y0ewSYiaDWH0K83+e70YUdROvk+FSNN3fCCEJHmxJlktjXjytyp9dKeEvyfsdB71TYapc/+Jgf4O+AoA9ZdIDJABU3DMqpfiYKA2BV9oQKMLPnduRbRKDxUP8vHcwzJ5z0IAwIMbk0eR4W2Ez8XLzjIV1SV8H1kfJqG2ItvxY9GZa1E+ZtZeu2vL7vdA0k2sYjTvXlxOhQXIMaqJOseEiijLWMK7KqtP7zSX4pNC8pmrsQ+p/NbtelZ/5oS9hKhNUKE3mSR8LqAehD7qNYDAk5muAJ5HbZ0ay2pTUCI1YKN+8ukXizNDS/2dy8hYvSP48kcPJFo2moYN063ZdtFnzFbmys=
  on:
    tags: true
  skip_existing: true
